#' Common first names given country
#'
#' This dataset contains common first names generated by ChatGPT
#' for selected countries.
#'
#' @format A data frame with 1380 rows and 3 variables:
#' \describe{
#'   \item{Country}{Country}
#'   \item{First_Name}{First name}
#'   \item{Sex}{Sex, Male or Female}
#' }
"first_names"

#' Common last names given country
#'
#' This dataset contains common last names generated by ChatGPT
#' for selected countries.
#'
#' @format A data frame with 449 rows and 2 variables:
#' \describe{
#'   \item{Country}{Country}
#'   \item{Last_Name}{Last name}
#' }
"last_names"

#' Patient initialization table
#'
#' There are a series of rows that describe a unique and mutually exclusive
#' category of individuals based on age group, sex, and pregnancy status. This
#' data is transformed from the TX_CURR indicator from the 2023 PEPFAR MSDs.
#'
#' @format A data frame with 2010 rows and 5 variables:
#' \describe{
#'   \item{operatingunit}{Country name}
#'   \item{sex}{Sex, Male or Female}
#'   \item{agegroup}{Age Group, "<15", "15+", "<01", "65+", and five-year increments from 1-65}
#'   \item{preg_satus}{Prenancy Status, "pregnant" or "not pregnant"}
#'   \item{prob}{Probability}
#' }
"age_sex_preg"

#' Interaction type probabilities
#'
#' Probabilities associated with each interaction type
#'
#' @format A data frame with 4 rows and 2 variables:
#' \describe{
#'   \item{interaction_type}{Interaction type}
#'   \item{prob}{Probabilities}
#' }
"interaction_type_probs"

#' Laboratory names
#'
#' A data frame of laboratory names. Laboratory names are randomly generated
#' and reflect national, regional, and hospital labs.
#'
#' @format A data frame with 1080 rows and 2 variables:
#' \describe{
#'   \item{country}{Country Name}
#'   \item{lab_name}{Laboratory Name}
#' }
"lab_names"

#' Clinic names
#'
#' A data frame of clinic names. Clinic names derived from sites reporting
#' TX_CURR data for 2024.
#'
#' @format A data frame with 27,324 rows and 3 variables:
#' \describe{
#'   \item{sitename}{Site Name}
#'   \item{country}{Country Name}
#'   \item{sitetype}{Type of Site, "Community" or "Facility"}
#' }
"clinic_names"

#' Blood pressure measurements
#'
#' A data frame defining reasonable blood pressure ranges by age. Min and max
#' values are derived from NHANES 2015-2018 data and, therefore, assume population
#' distribution of blood pressure values in the country of interest is similar
#' to that of the U.S. The 5th percentile was taken as the min and the 95th
#' percentile was taken as the max.
#'
#' Values for pediatric age groups not yet available.
#'
#' @format A data frame with 6 rows and 5 variables:
#' \describe{
#'   \item{age_band}{Age Group, <1, 1-4, 5-9, 10-14, 15-19, 20+}
#'   \item{sys_lo}{Minimum value for systolic bp in mm Hg}
#'   \item{sys_hi}{Maximum value for systolic bp in mm Hg}
#'   \item{dia_lo}{Minimum value for diastolic bp in mm Hg}
#'   \item{dia_hi}{Maximum value for diastolic bp in mm Hg}
#' }
"bp_systolic_diastolic"

#' Height measurements
#'
#' A data frame defining reasonable height ranges by age. Min and max
#' values are derived from NHANES 2015-2018 data and, therefore, assume population
#' distribution of height values in the country of interest is similar
#' to that of the U.S. The 5th percentile was taken as the min and the 95th
#' percentile was taken as the max.
#'
#'
#' @format A data frame with 6 rows and 3 variables:
#' \describe{
#'   \item{age_band}{Age Group, <1, 1-4, 5-9, 10-14, 15-19, 20+}
#'   \item{height_lo}{Minimum value for height in cm}
#'   \item{height_hi}{Maximum value for height in cm}
#' }
"height_in_cm"

#' Weight measurements
#'
#' A data frame defining reasonable weight ranges by age. Min and max
#' values are derived from NHANES 2015-2018 data and, therefore, assume population
#' distribution of weight values in the country of interest is similar
#' to that of the U.S. The 5th percentile was taken as the min and the 95th
#' percentile was taken as the max.
#'
#'
#' @format A data frame with 6 rows and 3 variables:
#' \describe{
#'   \item{age_band}{Age Group, <1, 1-4, 5-9, 10-14, 15-19, 20+}
#'   \item{height_lo}{Minimum value for weight in kg}
#'   \item{height_hi}{Maximum value for weight in kg}
#' }
"weight_in_kg"

#' ARV side effects
#'
#' This dataset is a list of regimens and their associated side effects, derived
#' from Chat GPT. Each row represents a side effect-regimen pair.
#'
#'
#' @format A data frame with 71 rows and 4 variables:
#' \describe{
#'   \item{side_effect}{Side effect}
#'   \item{regimen_abbv}{Abbreviation of the regimen}
#'   \item{regimen_desc}{Name of regimen}
#'   \item{side_effect_rarity}{Rarity of listed side effect for the regimen.
#'   "Rare" indicates rare side effect. NULL indicates common.}
#' }
"arv_side_effects"
